apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: default  
patches:
  - target:
      kind: Deployment
      name: retail-store-ui
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: retail-store-ui
        labels:
          app: retail-store-ui
      spec:
        replicas: 4
  - target:
      kind: StatefulSet
      name: catalogdb-statefulset
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: catalogdb-statefulset
      spec:
        serviceName: catalogdb-service
        replicas: 1