apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: retail-store-test
  region: eu-north-1

managedNodeGroups:
  - name: retail-workers
    instanceType: t3.medium
    minSize: 2
    desiredCapacity: 2
    maxSize: 2

    privateNetworking: true

    volumeSize: 30
    volumeType: gp3

    iam:
      withAddonPolicies:
        autoScaler: true