apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-catalog
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/mmzaboys/Hacathon-GitOps.git
    targetRevision: Mahmoud/EKS-adjustments
    path: data/catalog-db     # its own subfolder, just Catalog_mariadb.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true