apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/mmzaboys/Hacathon-GitOps.git
    targetRevision: Mahmoud/EKS-adjustments
    path: infra/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true